spring.datasource.url=jdbc:mysql://localhost:3306/sdcems
spring.datasource.username=root
spring.datasource.password=S@rthak20

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=8080
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB